CREATE DATABASE ECOMMERCE;
-- DROP DATABASE ECOMMERCE;

CREATE TABLE CUSTOMERS
(
CustomerID INT NOT NULL,
CustomerName VARCHAR(100),
ContactName	VARCHAR(100),
Address	VARCHAR(100),
City VARCHAR(100),
PostalCode INT,
Country VARCHAR(100),
PRIMARY KEY (CustomerID)
);

-- DROP TABLE CUSTOMERS; -- DELETES THE TABLE
-- DELETE FROM CUSTOMERS; -- DELETES ALL RECORDS BUT NOT TABLE
-- TRUNCATE TABLE CUSTOMERS; -- DELETES ALL RECORDS BUT NOT TABLE

-- ALTER TABLE CUSTOMERS
-- ADD MOBINE_NUM INT;

-- ALTER TABLE CUSTOMERS
-- DROP COLUMN MOBINE_NUM;

-- ALTER TABLE CUSTOMERS
-- MODIFY MOBINE_NUM LONG;

-- ALTER TABLE Orders
-- ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);

-- ALTER TABLE Orders
-- DROP FOREIGN KEY FK_PersonOrder;

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS
(
CustomerID,
CustomerName,
ContactName,
Address,
City,
PostalCode,
Country
)
VALUES
(
102,
"RUTUJA KAMBLE",
"RUTUJA",
"MANJARI",
"PUNE",
412307,
"INDIA"
),
(
103,
"ANJALI JADHAV",
"ANJALI",
"DADAR",
"MUMBAI",
400014,
"INDIA"
),
(
104,
"SAKSHI KASBE",
"SAKSHI",
"PARK STREET",
"LONDON",
200201,
"UK"
),
(
105,
"PRATIK SHINDE",
"PRATIK",
"DUBAI",
"DUBAI",
3003001,
"UAE"
),
(
106,
"MAHESH K",
"MAHESH",
"LA",
"LA",
1001001,
"USA"
);

DROP TABLE CUSTOMERS;

UPDATE CUSTOMERS
SET CUSTOMERNAME="MAHESH KESKAR"
WHERE CUSTOMERID IN (106,103,102,104);

SELECT * FROM CUSTOMERS WHERE COUNTRY NOT IN ("INDIA", "USA");

SELECT * FROM CUSTOMERS WHERE CustomerID BETWEEN 103 AND 105;

SELECT * FROM CUSTOMERS WHERE CustomerID=103 OR CustomerID=105;

SELECT * FROM CUSTOMERS WHERE CustomerID > 103 AND CustomerID < 106;

SELECT * FROM CUSTOMERS WHERE CustomerID >= 103 AND CustomerID <= 106;

SELECT * FROM CUSTOMERS WHERE CustomerID != 103 AND CustomerID < 105;


CREATE TABLE Supplier (
SupplierID INT	NOT NULL,
SupplierName VARCHAR(100),
ContactName VARCHAR(100),
Address VARCHAR(100),
City VARCHAR(100),
PostalCode INT,
Country VARCHAR(100),
Phone LONG,
PRIMARY KEY(SupplierID)
);

ALTER TABLE supplier
MODIFY Phone VARCHAR(100);


INSERT INTO Supplier( SupplierID, SupplierName, ContactName, Address, City, PostalCode, Country, Phone)
VALUES ( 1, "FOX CON",	"Charlotte Cooper",	"49 Gilbert St.","Londona","EC1 4SD","UK", "(171) 555-2222");

SELECT * FROM Supplier;

DELETE FROM CUSTOMERS WHERE CUSTOMERID=101;

SELECT * FROM customers;

SELECT COUNT(*) AS COUNT FROM customers;
SELECT SUM(CustomerID) AS SUM FROM customers;
SELECT distinct(COUNTRY) AS DISTINCT_COUNTRIES FROM customers;